---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  cookbooks_path: test/fixtures/cookbooks
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: centos-7.4

suites:
  - name: standalone
    provisioner:
      policyfile_path: policies/standalone.rb

  - name: replset1
    driver:
      network:
        private_network:
          ip: "172.16.20.10"
    provisioner:
      policyfile_path: policies/replset.rb

  - name: replset2
    driver:
      network:
        private_network:
          ip: "172.16.20.11"
    provisioner:
      policyfile_path: policies/replset.rb

  - name: replset-hidden
    driver:
      network:
        private_network:
          ip: "172.16.20.12"
    provisioner:
      policyfile_path: policies/replset.rb

  - name: replset3
    driver:
      network:
        private_network:
          ip: "172.16.20.13"
    provisioner:
      policyfile_path: policies/replset_init.rb

  - name: shard1
    driver:
      network:
        private_network:
          ip: "172.16.20.21"
    provisioner:
      policyfile_path: policies/shard.rb

  - name: shard2
    driver:
      network:
        private_network:
          ip: "172.16.20.22"
    provisioner:
      policyfile_path: policies/shard.rb

  - name: cfg1
    driver:
      network:
        private_network:
          ip: "172.16.20.23"
    provisioner:
      policyfile_path: policies/cfg.rb

  - name: cfg2
    driver:
      network:
        private_network:
          ip: "172.16.20.24"
    provisioner:
      policyfile_path: policies/cfg.rb

  - name: cfg3
    driver:
      network:
        private_network:
          ip: "172.16.20.25"
    provisioner:
      policyfile_path: policies/cfg_init.rb

  - name: shard_set1
    driver:
      network:
        private_network:
          ip: "172.16.20.26"
    provisioner:
      policyfile_path: policies/shard_set.rb

  - name: shard_set2
    driver:
      network:
        private_network:
          ip: "172.16.20.27"
    provisioner:
      policyfile_path: policies/shard_set.rb

  - name: shard_set3
    driver:
      network:
        private_network:
          ip: "172.16.20.28"
    provisioner:
      policyfile_path: policies/shard_init.rb

  - name: mongos
    driver:
      network:
        private_network:
          ip: "172.16.20.29"
    provisioner:
      policyfile_path: policies/mongos.rb
